Ui issues
ordbridge/bridgefrontend pull request #1
Opened 2023-12-26 18:16 UTC by hg133313

2023-12-26 18:33 UTC, techordb requested changes
Thanks for the fix 👍 , please do these minor changes

2023-12-26 18:33 UTC, techordb commented on src/components/Dropdown/index.jsx
> +import React, { useState } from 'react';
The edges on hover should be rounded
![Uploading Screen Shot 2023-12-27 at 3.29.06 AM.png…]()

2023-12-26 18:33 UTC, techordb commented on src/pages/HomePage.jsx
> +        <button
![Screen Shot 2023-12-27 at 3 30 06 AM](https://github.com/ordbridge/bridgefrontend/assets/153970940/84bb2c20-c32b-4073-abcc-db4a77fb8031)
This should not be visible when the user is already at the top

2023-12-27 10:07 UTC, techordb approved these changes

2023-12-27 10:08 UTC, isnemesis approved these changes

2023-12-27 10:09 UTC, merged